### ISSUE TITLE
How to include the java compiler so that ToolProvider.getSystemJavaCompiler() is not null

### ISSUE THREAD

**Issue by artpar** [sourcebuddy/sourcebuddy#4]
I seem to be missing something very basic here. `ToolProvider.getSystemJavaCompiler()` returns null if tools.jar (which seems to be removed after java 1.8) isn't included in the final artifact (in my case I am working on a eclipse plugin).

How should I make use of this ?

In my use case I can assume that the final user does have JDK available on their system and I know the path to it as well, but I don't see any way to configure that call to point it to the JDK.

**Comment by verhas** [comment]
I am afraid that the answer to this question is that the application must be executed using a JDK. The compiler used by SourceBuddy is part of the JDK, but it is not part of the JRE, as far as I know.

To be honest, I thought that after Java 8, there is no separate JRE for Java. When you go to the java.com page and follow the JRE download, it will give you the JRE8u381 version, which is Java 8.

If the user has  JDK, then what is the reason they are using a different JRE to run Eclipse or some other application?

**Comment by artpar** [comment]
They are using JDK to use their IDE (intellij in this case), and I can explicitly in invoke the application using JDK, which I believe is already happening when the application starts in "debug" mode, but I still see null return from that call. So I am a bit lost as to what am I missing.

**Comment by verhas** [comment]
Go to Help -> Find Action in the IntelliJ menu. Start typing "Choose Boot Runtime," and press 'enter'.
It will bring up a modal box that shows the JDK executing the IntelliJ IDE itself and also lets you change it.

![image](https://user-images.githubusercontent.com/1597979/228473508-58630fc5-0775-48c2-bced-989d65a56baa.png)

It is usually a run-time provided by IntelliJ bundled with the IDE. It may not contain all the parts of the JDK that you may need.

Changing the Boot Runtime is described on the IntelliJ documentation page https://www.jetbrains.com/help/idea/switching-boot-jdk.html

**Comment by artpar** [comment]
Thanks Peter
