### ISSUE TITLE
need clarification on Java requirement to use  SourceBuddy

### ISSUE THREAD

**Issue by gtiwari2015** [sourcebuddy/sourcebuddy#5]
Hi,

I am evaluating to sourcebuddy to dynamically create compile java classes. In our java environment only JRE is available . Please let me know  whether is there any requirement of JDK as well or only JRE is ok to use .

Thanks
Gaurav

**Comment by verhas** [comment]
Different installations may lack some of the Java features. I cannot tell what your installation supports, but most probably, you will need JDK. I also do not know why it is only JRE in your environment, but one reason may be that the people providing the environment do not want you to use tools like SourceBuddy.

**Comment by gtiwari2015** [comment]
Thanks for your reply. We ship our products to customer with the required
JRE  version only and due to security reasons and size of product
deliverable we can use JRE.as we don't want to use tools.jar available in
jdk ,we are looking some 3rd party libraries where javac is present to
compile generated classes at run time  .

Thanks
GAURAV

**Comment by verhas** [comment]
I've kept this issue open for a while to allow the original reporter to add any necessary comments.
