### ISSUE TITLE
Compile and load an enum

### ISSUE THREAD

**Issue by decebals-btcs** [sourcebuddy/sourcebuddy#6]
I have a java file with below content

```java

package acme;

public enum OnboardingStatus {
    NOT_STARTED,
    IN_PROGRESS,
    COMPLETED;
}
```

When I try to compile and load the enum using Compiler#compile(String source) I encounter the below error:
```
Caused by: java.lang.ClassNotFoundException: Cannot find the package and/or class declaration in the source code
	at com.javax0.sourcebuddy.Compiler.getBinaryNameFromSource(Compiler.java:1013)
	at com.javax0.sourcebuddy.Compiler.from(Compiler.java:497)
```

and this is because `CLASS_PATTERN.matcher(sourceCode)` returns false (no 'class' word found).

Is it a bug or what?

**Comment by verhas** [comment]
It is a bug if you like. The code looks for classes and it an enum. You have an API and you can provide the name if the "class" is a separate call. It is documented. If you need more help i will do in 14 hours.

**Comment by decebals-btcs** [comment]
I solved the problem based on your recommendation. 
It will be nice if you could fix the error in the future releases.
Thanks, I appreciate your effort in Java ecosystem (I know your work 😄) !

**Comment by verhas** [comment]
It is not really a bug, as the behavior you observed is documented. The current implementation of Compiler#compile(String source) uses a regular expression to recognize only 'class' names in the source code. This is why the CLASS_PATTERN.matcher(sourceCode) returns false when encountering an 'enum' type.

However, I understand the limitations this imposes, and I appreciate your feedback. Extending the regular expression to recognize 'interface', 'enum', and 'record' declarations should be a good enough solution. This enhancement will allow the compiler to handle more types of source code more flexibly.

Another approach is to use a lexical analyzer. Lexical analyzers available for Java could handle this more comprehensively. However, adding such an external dependency might be a bit too much for this use case, and I want to keep the implementation as lightweight as possible.

Going further to a syntax analyzer would indeed be an overkill for the current scope of this project.

I will add support for 'interface', 'enum', and 'record' declarations to the regular expression in the package's next release. This should address the issue you encountered.

Thank you for your patience and for helping to improve SourceBuddy!

**Comment by verhas** [comment]
Since the 2.5.1 release is out and available from Nexus Central, providing a fix for this issue, I am closing this ticket now.
