### ISSUE TITLE
Use File.separator insted of '/' char in Compiler#from(Path fileOrDir)

### ISSUE THREAD

**Issue by decebals-btcs** [sourcebuddy/sourcebuddy#8]
So, the [current code](https://github.com/sourcebuddy/sourcebuddy/blob/main/src/main/java/com/javax0/sourcebuddy/Compiler.java#L604) doesn't work well on Windows systems

**Comment by verhas** [comment]
You are right. The fix will be available as the release 2.5.3 from Maven Central in a few minutes as the processing on the repo server finishes.
